"""Crash-recovery finding: content/articles/nitrat.html was a real,
gate-passing article generated by a manual end-to-end run of the content
pipeline (validating the final-publication-gate fix) with no Commander
commitment behind it. _first_staged_slug() -- the function the real
deployment capability (_execute_deployment) uses to decide which article to
git-add, commit, and push to production -- treated any untracked
content/articles/*.html file as deployable, purely from git-tracking state.
Had Commander selected deployment while that file existed, this would have
committed and pushed a manual verification artifact to the live site.

This is the safety-critical half of the fix: deployment must refuse to
consider an untracked article that has no CONFIRMED content_production/
legacy_migration commitment recording a passed publication gate for that
exact slug.
"""

from __future__ import annotations

import importlib.util
import hashlib
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
_spec = importlib.util.spec_from_file_location("levnytt_procedure", ROOT / "commander" / "procedure.py")
procedure = importlib.util.module_from_spec(_spec)
sys.modules[_spec.name] = procedure
_spec.loader.exec_module(procedure)

_first_staged_slug = procedure._first_staged_slug
_provenance_verified_slugs = procedure._provenance_verified_slugs


def _git(*args: str, cwd: Path) -> None:
    subprocess.run(["git", *args], cwd=str(cwd), check=True, capture_output=True, text=True)


def _write_commitments(repo: Path, commitments: list[dict]) -> None:
    path = repo / "runtime" / "commander" / "commitments.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps({"commitments": commitments}), encoding="utf-8")


def _confirmed_commitment(slug: str, *, capability_id: str = "content_production", **evidence) -> dict:
    return {
        "capability_id": capability_id,
        "status": "CONFIRMED",
        "resolution_reason": str({"slug": slug, "gate_passed": True, "staged_path": f"/repo/content/articles/{slug}.html", **evidence}),
    }


def _init_repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    (repo / "content" / "articles").mkdir(parents=True)
    _git("init", "-q", cwd=repo)
    _git("config", "user.email", "test@example.com", cwd=repo)
    _git("config", "user.name", "Test", cwd=repo)
    return repo


def test_legitimate_commander_produced_staged_article_is_deployable(tmp_path: Path):
    repo = _init_repo(tmp_path)
    (repo / "content" / "articles" / "real-slug.html").write_text("<h1>Real</h1>", encoding="utf-8")
    _write_commitments(repo, [_confirmed_commitment("real-slug")])

    assert _first_staged_slug(repo) == "real-slug"


def test_manual_verification_artifact_is_never_selected_for_deployment(tmp_path: Path):
    """The exact nitrat.html shape: gate-passing HTML on disk, zero
    commitment. Deployment must see no staged work here, not silently
    commit and push it."""
    repo = _init_repo(tmp_path)
    (repo / "content" / "articles" / "nitrat.html").write_text("<h1>Nitrat</h1>", encoding="utf-8")
    _write_commitments(repo, [])

    assert _first_staged_slug(repo) is None


def test_deployed_article_is_not_reselected(tmp_path: Path):
    repo = _init_repo(tmp_path)
    article = repo / "content" / "articles" / "deployed-slug.html"
    article.write_text("<h1>Deployed</h1>", encoding="utf-8")
    _git("add", "content/articles/deployed-slug.html", cwd=repo)
    _git("commit", "-m", "Publish NeoLife article: deployed-slug", cwd=repo)
    _write_commitments(repo, [_confirmed_commitment("deployed-slug")])

    assert _first_staged_slug(repo) is None


def test_hash_bound_content_improvement_selects_only_the_confirmed_existing_bytes(tmp_path: Path):
    repo = _init_repo(tmp_path)
    data = repo / "content" / "data" / "production-pages.json"
    data.parent.mkdir(parents=True)
    article = repo / "existing.html"
    article.write_text("<h1>Original</h1>", encoding="utf-8")
    data.write_text('{"pages": []}', encoding="utf-8")
    _git("add", "existing.html", "content/data/production-pages.json", cwd=repo)
    _git("commit", "-m", "seed", cwd=repo)
    article.write_text("<h1>Improved</h1>", encoding="utf-8")
    data.write_text('{"pages": [{"path": "/existing"}]}', encoding="utf-8")
    sha = lambda path: hashlib.sha256(path.read_bytes()).hexdigest()
    _write_commitments(repo, [_confirmed_commitment(
        "existing",
        capability_id="content_improvement",
        source_file="existing.html",
        staged_content_sha256=sha(article),
        production_data_sha256=sha(data),
    )])

    assert _first_staged_slug(repo) == "existing"
    assert procedure._staged_article_path(repo, "existing") == article

    article.write_text("<h1>Later manual edit</h1>", encoding="utf-8")
    assert _first_staged_slug(repo) is None
    assert procedure._staged_article_path(repo, "existing") is None


def test_random_modified_existing_page_without_commitment_is_never_selected(tmp_path: Path):
    repo = _init_repo(tmp_path)
    article = repo / "manual.html"
    article.write_text("<h1>Original</h1>", encoding="utf-8")
    _git("add", "manual.html", cwd=repo)
    _git("commit", "-m", "seed", cwd=repo)
    article.write_text("<h1>Manual change</h1>", encoding="utf-8")
    _write_commitments(repo, [])

    assert _first_staged_slug(repo) is None
    assert procedure._staged_article_path(repo, "manual") is None


def test_mixed_pool_only_returns_the_verified_slug(tmp_path: Path):
    """A verification artifact sitting alongside a genuine staged article
    must never block or substitute for the real one."""
    repo = _init_repo(tmp_path)
    (repo / "content" / "articles" / "aaa-manual-artifact.html").write_text("<h1>M</h1>", encoding="utf-8")
    (repo / "content" / "articles" / "zzz-real-slug.html").write_text("<h1>R</h1>", encoding="utf-8")
    _write_commitments(repo, [_confirmed_commitment("zzz-real-slug")])

    assert _first_staged_slug(repo) == "zzz-real-slug"


def test_missing_commitments_file_yields_no_provenance(tmp_path: Path):
    repo = _init_repo(tmp_path)
    (repo / "content" / "articles" / "orphan.html").write_text("<h1>O</h1>", encoding="utf-8")

    assert _provenance_verified_slugs(repo) == set()
    assert _first_staged_slug(repo) is None
